### ISSUE TITLE
Tracking of Bugs in Nodes while refactoring

### ISSUE THREAD

**Issue by BradyAJohnston** [BradyAJohnston/MolecularNodes#119]
- [x] MOL_style_atoms if vdw_radii is 0 or doesn't exist should default to a sensible value
- [x] MOL_animate_frames doesn't have an option to turn off frame interpolation
- [x] MOL_animate_frames should have an option for a field to be interpolated as well (or potentially a new node?)
- [x] reporting for MD import is too verbose, can trim the file paths as they are already set by the user
- [x] Multiple MOL_atomic_material's being created on import
- [x] create more specialised shader for MOL, can just be appended rather than created manually

**Comment by BradyAJohnston** [comment]
all addressd inside of [2.1 release](https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v2.1.0)
