### ISSUE TITLE
Implement Access and Stream Trajectories with MDAnalysis inside MolecularNode

### ISSUE THREAD

**Issue by yuxuanzhuang** [BradyAJohnston/MolecularNodes#292]
### Issue Description:
We are planning to enhance the capabilities of MolecularNodes by integrating the ability to access and stream trajectories using MDAnalysis. This feature would enable users to
- efficiently load molecular dynamics trajectories without dumping all the frames into memory.
- leverage the power of Blender as a live viewer for trajectories e.g. inside a jupyter notebook with [BNotebooks](https://github.com/BradyAJohnston/BNotebooks) Blender kernel.
- pave the way for scripting rendering pipelines.

### Proposed Design:
To implement this feature, we propose the following design in scripting:

#### start a session
```python
mda_session = mn.mda.MDAnalysisSession(world_scale=0.01)
```

#### show atoms

```python
universe = mda.Universe(top, traj)

custom_selections = {'name_ca': 'name CA', 'ion': 'resname SOD CLA'}

# This will create three representations inside Blender
mda_session.show(universe, name='protein', selection='protein', custom_selections=custom_selections)

# Add new representations for new selected atoms
ligand = universe.select_atoms('resname LIG')
mda_session.show(ligand, name='ligand', representation='ball+stick')

# Add representations for dynamically selected selected atoms
around_ligand = universe.select_atoms('protein and byres (around 4 resname LIG)', updating=True)
mda_session.show(around_ligand, name='around_lig', representation='vdw')

# add new trajectory and an offset of the frame can be set
universe2 = mda.Universe(top2, traj2)
mda_session.show(universe2, name='protein', selection='protein', frame_offset=100)
```

#### Persistence

```python
# saving
file_path = "blender_and_mda.blend"
bpy.ops.wm.save_as_mainfile(filepath=file_path)

# loading
bpy.ops.wm.open_mainfile(filepath=file_path)
mda_session = bpy.context.scene.mda_session
universe = mda_session.universe

# persistent even when trajectory files are deleted
mda_session.transfer_to_memory(start, step, end)

# or use legacy code with Blender UI
```

Example:
- showcase: https://drive.google.com/file/d/1A_WlN8oUaMqjV6MsKP4F2lSvtRKa6YVt/view?usp=sharing
- notebook: https://gist.github.com/yuxuanzhuang/25aa5a1588c7e19efbfc1b7275718b58
### Expected Benefits:
- a consistent python API to interact between Blender and MDAnalysis
- better organization of atoms representations
- Memory efficiency
- [On-the-fly transformations](https://userguide.mdanalysis.org/stable/trajectories/transformations.html) e.g. fixing PBC, designed rotation, smoothing (position averaging).

### Expected Caveats:
- the current implementation of blender kernel will open blender automatically in the initialization stage. Ideally, it should be only after a new MDAnalysisSession is started.
- Need to have a consistent connection to the trajectory in the session.
- During the animation, the state of the Universe will be altered. A racing condition is likely to get induced when the trajectory frames are iterated in the notebook simultaneously.
- `MDAnalysisSession` (together with `Universe`) will be dumped into a tmp location during saving .blend file i.e. `~/.blender_mda_session/` by default.
- a relative path of trajectory is saved for Universe -> where does Blender start matters!
- ~~potentially create conflicts with the current animation engine and the selection process within the geometric node.~~

### Tasks (~~task~~ will not be implemented in this PR):
- [x] Design and implement `MDAnalysisSession` and `AtomGroupInBlender`.
- [x] Loading and Saving (Persistence)
- [x] Deletion
- [x] Start with different representations
- [ ] ~~Function to switch representations~~
- [x] `Atomgroup` with variable n_atoms i.e. a dynamic selection of atoms
- [ ]  ~~Update attributes if the topology is modified~~
- [x] Multiple universes
- [ ] ~~ways to add new time-evolved attributes and display in blender (e.g. occupancy)~~
- [ ] Benchmark on streaming
- [x] Write unit tests to ensure reliability and stability.
- [x] Update documentation/tutorial to reflect the new feature and its usage.

### Future direction
- visualize analysis results e.g. simple distances, angles, etc.

**Comment by BradyAJohnston** [comment]
Thanks for writing this up! It's exciting to have so much potential in an idea that is already most of the way there. For the caveats, I don't think clashes with the currently implemented animation or selection system inside of Geometry Nodes will be a problem. Already we have seen by just not adding the animation node, everything pretty much works out of the box.

Ping @tubiana I think you would be interested in this. There is already some working examples showing interaction between notebooks and a live Blender session, streaming the MDAnalysis universe. 


[![Example Notebook](https://img.youtube.com/vi/gn-1i_Qikbs/maxresdefault.jpg)](https://www.youtube.com/watch?v=gn-1i_Qikbs)
